config/routes.rb
  # resources :users, only: [:show, :update] do
  #   get     :show_alert, on: :member
  #   get     :new_alert, on: :member
  #   get     :edit_alert, on: :member
  #   patch   :update_alert, on: :member
  #   delete  :destroy_alert, on: :member
  #   post    :create_alert, on: :member
  #   post :become, on: :collection
  #   resources :user_roles do
  #     get :descriptions_by_role, on: :collection
  #   end
  # end

  resources :companies do
    member do
      get :charts_filter
      get :vendor_charts
      get :vendor_client_charts
      get :vendor_charts_quantity
      get :vendor_client_charts_quantity
    end
  end

  resources :external_bills do
    get :open, on: :member
    get :add_detail, on: :collection
    get :index_by_client, on: :collection
  end

  resources :external_arrivals do
    get :new_batch_detail, on: :collection
    get :open, on: :member
    get :index_by_file, on: :collection
    get :add_detail, on: :collection
    get :import, on: :collection
    get :new_stock, on: :collection
    post :create_stock, on: :collection
  end

  resources :external_shipments do
    get :new_batch_detail, on: :collection
    get :open, on: :member
    get :index_by_file, on: :collection
    get :add_detail, on: :collection
    get :import, on: :collection
    get :stock, on: :collection
    get :new_stock, on: :collection
    post :create_stock, on: :collection
  end

  resources :expedient_bills

  resources :supplier_tracings, only: :index
  scope module: :entities do
    scope module: :suppliers do
      resource :supplier_contacts do
        get :index_by_supplier, on: :collection
      end
      resources :suppliers do
        post :import, on: :collection
        get :index_by_company, on: :collection
				post :import, on: :collection

        resources :supplier_account_movements
        get :products, on: :member
        resources :supplier_contacts do
          resources :supplier_contact_records
        end
      end
    end
    scope module: :clients do
      resources :entity_banks
      resources :clients do
        get :index_by, on: :collection
				post :import, on: :collection
        get :debt, on: :member
        resources :client_account_movements
        resources :client_contacts do
          resources :client_contact_records
        end
      end
      resources :client_contacts do
        resources :client_contact_records, controller: :contact_records
      end
    end
  end



  scope module: :inventaries do
    resources :product_categories
    resources :products do
      get :filter_by_supplier, on: :collection
      get :filter_by_product, on: :collection
      get :filter_by_delivered_product, on: :collection
      post :import, on: :collection
      get :export, on: :collection
      get :valores_stock, on: :collection
      get :valores_stock_totales, on: :collection
      get :import_format, on: :collection
      get :index_by_company, on: :collection
      patch :fix_stock, on: :member
      get :new_clean_stock, on: :member
      post :clean_stock, on: :member
      resources :batches, only: [:index, :show, :destroy] do
        get :new_clean_stock, on: :member
        post :clean_stock, on: :member
        get :unit_gtins, on: :member
        get :availables, on: :collection
      end
    end
    resources :inventaries do
      get :sale_price_history, on: :member
      get :purchase_price_history, on: :member
      get :stock, on: :member
    end
    resources :boxes do
      get :search, on: :collection
    end
    resources :stores do
      get :products, on: :member
    end
  end

  resources :expedient_movements
  resources :expedient_receipts do
    get :open, on: :member
    get :assign_bill_to, on: :member
    post :import, on: :collection
  end

  namespace :agreement_surgeries do 
    resources :surgery_materials do
      get :index_by_company, on: :collection
      get :edit_update_prices, on: :collection
      post :update_prices, on: :collection
    end
    resources :price_updates
    resources :surgery_requests do
      member do 
        get :pre_rechazar
        patch :rechazar
        put :aprobar
        put :coordinar
        put :recuperar
        put :a_espera_procesamiento
        put :crear_expediente
      end
    end
    resources :files do
      get :index_by_company, on: :collection
      get :get_file_data, on: :member
    end
    resources :sale_orders do
      get :index_by_company, on: :collection
      get :open, on: :member
      get :deliver, on: :member
      get :get_details, on: :collection
    end
    resources :budgets  do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :index_by_client, on: :collection
      get :deliver, on: :member
    end
    resources :shipments do
      get :new_batch_detail, on: :collection
      get :open, on: :member
      get :index_by_client, on: :collection
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :deliver, on: :member
      get :check_stock, on: :member
      get :get_details, on: :collection
      patch :conform, on: :member
    end
  end


  namespace :surgeries, path: 'surgeries' do
    resources :calendars, only: :index
    resources :excel_surgeries
    resources :files do
      get     :display_alerts, on: :member
      get     :show_alert, on: :member
      get     :new_alert, on: :member
      get     :edit_alert, on: :member
      patch   :update_alert, on: :member
      delete  :destroy_alert, on: :member
      post    :create_alert, on: :member
      get     :get_file_data, on: :member
      get     :index_by_client, on: :collection
      get     :index_by_company, on: :collection
      get     :vencidos, on: :collection
      put     :excluir_de_vencidos, on: :member
      get     :for_calendar, on: :collection
      get :new_cambiar_seller
      post :create_cambiar_seller
    end
    resources :arrivals do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :import, on: :collection
    end
    resources :prescriptions do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :index_by_client, on: :collection
      get :add_detail, on: :collection
    end

		resources :devolutions do
      get :new_batch_detail, on: :collection
			get :open, on: :member
      get :index_by_file, on: :collection
      get :index_by_supplier, on: :collection
      get :add_detail, on: :collection
    end
    resources :file_movements
    resources :supplier_requests do
      get :index_by_supplier, on: :collection
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
    end
    resources :purchase_requests do
      get :index_by_client, on: :collection
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
    end
    resources :purchase_orders  do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
			get :deliver, on: :member
    end
    resources :consumptions  do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :new_batch_detail, on: :collection
    end

    resources :shipments do
      get :new_batch_detail, on: :collection
      get :open, on: :member
      get :index_by_client, on: :collection
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :deliver, on: :member
      get :check_stock, on: :member
      get :get_details, on: :collection
      patch :conform, on: :member
    end

    resources :client_bills do
      get :associate_document, on: :collection
      get :open, on: :member
      get :add_detail, on: :collection
      get :index_by_client, on: :collection
      get :set_manual, on: :member
    end

    resources :supplier_bills do
      get :open, on: :member
      get :add_detail, on: :collection
      get :index_by_client, on: :collection
    end

    resources :budgets  do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :index_by_client, on: :collection
			get :deliver, on: :member
    end

    resources :sale_orders do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :index_by_client, on: :collection
      get :deliver, on: :member
      get :get_details, on: :collection
    end

    resources :receipts do
    end
  end

  namespace :purchases, path: 'purchases' do
    resources :files  do
      get     :show_alert, on: :member
      get     :new_alert, on: :member
      get     :edit_alert, on: :member
      patch   :update_alert, on: :member
      delete  :destroy_alert, on: :member
      post    :create_alert, on: :member
      get     :index_by_company, on: :collection
      get     :get_file_data, on: :member
    end
    resources :file_movements
    resources :purchase_requests do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :add_detail, on: :collection
      get :index_by_company, on: :collection
    end
    resources :orders do
      get :open, on: :member
      get :index_by_file, on: :collection
      get :index_by_supplier, on: :collection
      get :add_detail, on: :collection
      get :index_by_company, on: :collection
      get :deliver, on: :member
    end
    resources :devolutions do
      get :new_batch_detail, on: :collection
      get :open, on: :member
      get :index_by_file, on: :collection
      get :set_params_delivery_note, on: :member
      post :create_deliver_note, on: :member
      get :add_detail, on: :collection
      get :index_by_company, on: :collection
    end
    resources :budgets do
      get :open, on: :member
      get :index_by_file, on: :collection

app/models/file/sales/bill.rb
class Sales::Bill < ExpedientBill
  include Notificable
  include Reopener
  belongs_to :file, class_name: "Sales::File", foreign_key: :file_id
  belongs_to :client, foreign_key: :entity_id

  has_many :bills_orders, class_name: "Sales::BillOrder", foreign_key: :bill_id, inverse_of: :bill
  has_many :orders, through: :bills_orders
  has_many :bills_shipments, class_name: "Sales::BillShipment", foreign_key: :bill_id, inverse_of: :bill
  has_many :shipments, through: :bills_shipments
  has_many :shipment_details, through: :shipments, source: :details
  has_many :product_details, class_name: "Sales::BillInventary", foreign_key: :bill_id, inverse_of: :bill
  has_many :service_details, class_name: "Sales::BillService", foreign_key: :bill_id, inverse_of: :bill
  has_many :receipts_bills, class_name: "ExpedientReceiptBill"
  validates_presence_of :fch_vto_pago, message: "Debe especificar"

  inherit_details_from :order
  filter_details_from :shipment

  accepts_nested_attributes_for :bills_orders, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :bills_shipments, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :product_details, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :service_details, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :file, allow_destroy: true, reject_if: :all_blank

  after_validation :confirm

  after_save :set_account_movement
  after_save :create_shipment
  before_validation :set_due_date
  default_scope ->{where(flow: "income")}

  before_validation :at_least_one_order

  def at_least_one_order
    bills_orders.build if bills_orders.reject(&:marked_for_destruction?).size == 0
  end

  def department
    "Ventas"
  end

  def confirm
    BillManager::Confirmator.confirm(self) unless errors.any?
  end

  def set_account_movement
    ClientManager::SaleBillConfirmator.call(self) if recently_confirmed?
  end

  def create_shipment
    # if file.sale_type == "Venta por mostrador" && saved_change_to_state? && confirmed?
    #   SaleManager::ShipmentGenerator.new(self).call
    # end
  end

  def cbte_fch
    read_attribute(:cbte_fch) || Date.today
  end

  def cbte_tipo
    read_attribute(:cbte_tipo)
  end

  def has_credit_note?
    credit_notes.any?
  end

  def has_debit_note?
    debit_notes.any?
  end

  def associate bill_id
    details.each(&:mark_for_destruction)
    bill = company.sale_bills.find(bill_id)
    bill.details.each do |detail|
      details.build(detail.attributes.except(:id, :bill_id))
    end
  end

  def has_pdf?
    manual == "E"
  end

  def set_due_date
    self.fch_vto_pago = self.cbte_fch.to_date + self.due_days.to_i.days
  end

end

app/models/file/sales/bill_detail.rb
class Sales::BillDetail < ExpedientBillDetail
  include ProductInheritance
  belongs_to :bill, class_name: "Sales::Bill", foreign_key: :bill_id, inverse_of: :details, optional: true


  TABLE_COLUMNS = {
    "Número"        => {"important" => true,  "fixed" => false},
    "Tipo"          => {"important" => true,  "fixed" => false},
    "Vendedor"      => {"important" => true,  "fixed" => false},
    "Descripción"   => {"important" => true,  "fixed" => false},
    "Código"        => {"important" => true,  "fixed" => false},
    "Marca"         => {"important" => true,  "fixed" => false},
    "Cantidad"      => {"important" => true,  "fixed" => false},
    "Precio bruto"  => {"important" => true,  "fixed" => false},
    "Descuento (%)" => {"important" => false, "fixed" => false},
    "IVA (%)"       => {"important" => true,  "fixed" => false},
    "Subtotal"      => {"important" => true,  "fixed" => true },
    "Acción"        => {"important" => true,  "fixed" => true }
  }

  def assign_from_another(so_detail, recharge = 0.0, child = false, supplier_id = nil) # so_detail can be a child too
      #if so_detail.product_id.nil?
      #  self.mark_for_destruction
      #else
        self.reload if self.marked_for_destruction?
      #end
      self.product_id             = so_detail.product_id
      self.product_name           = so_detail.product_name
      self.product_measurement    = so_detail.inventary.medida unless so_detail.is_a_service?
      self.product_code           = so_detail.product_code || so_detail.product.code
      self.price                  += so_detail.price.round(4)
      self.iva_aliquot            = so_detail.iva_aliquot
      self.iva_amount             += so_detail.iva_amount.to_f
      self.discount               = so_detail.discount
      self.total                  += so_detail.total.round(4)
      self.subtype                = so_detail.is_a_service? ? "Sales::BillService" : "Sales::BillInventary"
      self.seller_id              = so_detail.user_id
      unless skip_filter_inheritance
        self.quantity               += so_detail.quantity - so_detail.bill_quantity.to_i
      else
        self.quantity               = so_detail.quantity
      end
      self.mark_for_destruction if self.quantity == 0
  end

  def is_a_product?
    self.subtype == "Sales::BillInventary"
  end

  def is_a_service?
    self.subtype == "Sales::BillService"
  end

  def tipo
    is_a_service? ? "Servicio" : "Producto"
  end
end

app/models/file/sales/bill_inventary.rb
class Sales::BillInventary < Sales::BillDetail
	self.inheritance_column = :subtype
	include ProductDetails
	
	has_many   :order_details,
              ->(detail){where(product_id: detail.product_id)},
              through: :orders,
              source: :details
    has_many   :shipment_details,
              ->(detail){where(product_id: detail.product_id)},
              through: :shipments,
              source: :details

	def parent
		bill
	end

end

app/models/file/sales/bill_order.rb
class Sales::BillOrder < ExpedientBillOrder
	belongs_to :bill, class_name: "Sales::Bill", inverse_of: :bills_orders
	belongs_to :order, class_name: "Sales::Order", optional: true

	validates_presence_of :order, message: "Debe asociar al menos una orden de venta", if: Proc.new{|o| o.bill.is?(:bill) && o.bill.file.sale_type == "Venta regular"}
end

app/models/file/sales/bill_service.rb
class Sales::BillService < Sales::BillDetail
	self.inheritance_column = :subtype
	self.ignored_columns = %w(product_id)
end

app/models/file/sales/bill_shipment.rb
class Sales::BillShipment < ExpedientBillShipment
	belongs_to :bill, class_name: "Sales::Bill", inverse_of: :bills_shipments
	belongs_to :shipment, class_name: "Sales::Shipment"
end

app/models/file/sales/budget_sale_request.rb
class Sales::BudgetSaleRequest < ExpedientBudgetRequest
  belongs_to :budget, class_name: "Sales::Budget", foreign_key: :budget_id, inverse_of: :budgets_sale_requests
  belongs_to :sale_request, class_name: "Sales::SaleRequest", foreign_key: :request_id, optional: true

  validates_presence_of :sale_request, message: "Debe asociar al menos una solicitud"
end

app/models/file/sales/file_movement.rb
class Sales::FileMovement < ExpedientMovement
	belongs_to :file, class_name: "Sales::File", foreign_key: :file_id
end

app/models/file/sales/order_budget.rb
class Sales::OrderBudget < ExpedientOrderBudget
	belongs_to :order, class_name: "Sales::Order", inverse_of: :orders_budgets,optional: true
	belongs_to :budget, class_name: "Sales::Budget",optional: true
end

app/models/file/sales/receipt.rb
class Sales::Receipt < ExpedientReceipt
	belongs_to 	:file, class_name: "Sales::File", foreign_key: :file_id

	has_many :details, class_name: "Sales::ReceiptBill", foreign_key: :receipt_id, inverse_of: :receipt
	has_many :bills, through: :details
	has_many :responsables, through: :bills

	accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true
end

app/models/file/sales/receipt_detail.rb
class Sales::ReceiptDetail < ExpedientReceiptDetail
end

app/models/file/sales/request_detail.rb
class Sales::RequestDetail < ExpedientRequestDetail
end

app/views/sales/_shared_attachment.html.haml
#attachments.card.shadow.mx-4.mb-4.collapse{data: {parent: "#document-accordion"}}
	.card-header.bg-white
		%h5.w-100.pt-2 Documentos adjuntos
	.card-body
		- unless f.object.disabled?
			.d-flex.attachments-fields
				= f.simple_fields_for :attachments, wrapper: false do |i|
					.row.mx-3.fields.with-title{class: "#{i.index}"}
						.caption.captionload
							= image_tag "/images/load.gif", class: 'img-fluid'
						.text-center.img_wrp
							= image_tag i.object.display_file, width: '90px', height: '75px', alt: 'Añadir imagen', class: "border img-fuild image #{i.object.new_record? ? 'hidden' : nil}", data: {index: i.index, source: i.object.file}
							- if i.object.new_record?
								= i.input :original_filename, value: i.object.original_filename, as: i.object.new_record? ? :hidden : :string, label: false, wrapper_html: {style: 'width: 90px'}
							- else
								.row.text-center
									= link_to i.object.original_filename, i.object.file, style: 'max-width: 200px', target: '_blank'
							= i.link_to_remove icon('fas', 'times'), class: 'rm-img-btn text-dark'
						= i.input :file, as: :file, input_html: { hidden: true, class: "file_input", data: {index: i.index, required: false} }, label: false
			= f.link_to_add "#{icon('fas', 'paperclip')} Adjuntar archivo".html_safe, :attachments, class: "btn btn-success btn-sm align-self-start #{'disabled' if f.object.disabled?}", data: {target: '.attachments-fields'} unless f.object.disabled?
			%center
				%hr
					= save_button unless f.object.disabled?
		- else
			.row
				- if f.object.attachments.any?
					- f.object.attachments.each do |attachment|
						.col-3
							.text-center.img_wrp
								= image_tag attachment.display_file, width: '90px', height: '75px', alt: 'Añadir imagen', class: "border img-fuild image", data: {source: attachment.file}
								.text-center
									= link_to attachment.original_filename, attachment.file, style: 'max-width: 200px', target: '_blank'
				- else
					%p.h4.col-12

						El documento actual no posee adjuntos

app/views/sales/_shared_details_form.html.haml
= hidden_field_tag :klass_validator, f.object.class.name
= f.simple_fields_for :details, defaults: {disabled: f.object.disabled?, label: false}, wrapper: false do |d|
	= render 'details_form', {d: d, child: false}
	- unless ["Sales::Bill", "Sales::Receipt", "Surgeries::SupplierBill", "Surgeries::ClientBill", "Surgeries::Receipt", "ExpedientReceipt"].include?(f.object.class.name)
		= d.simple_fields_for :childs, defaults: {disabled: f.object.disabled?, label: false}, wrapper: false do |c|
			= render 'details_form', {d: c, child: true, parent_index: d.index}

app/views/sales/_shared_links.html.haml
%li.nav-item
	= button_tag "#{icon('fas', 'list')} Conceptos".html_safe, type: :button, aria: {selected: true, controls: 'concepts'}, data: {toggle: 'tab', target: '#concepts', target: '#concepts'}, class: 'nav-link bg-white active'
= yield(:extra_links)
%li.nav-item
	= button_tag "#{icon('fas', 'eye')} Mostrar adjuntos".html_safe, type: :button, aria: {selected: false, controls: 'attachments'}, data: {toggle: 'tab', target: '#attachments'}, class: 'nav-link bg-white '
%li.nav-item
	= button_tag "#{icon('fas', 'ellipsis-v')} Campos adicionales".html_safe, type: :button, aria: {selected: false, controls: 'custom_attributes'}, data: {toggle: 'tab', target: '#custom_attributes'}, class: 'nav-link bg-white collapsed'
-if !["Sales::Receipt", "Tenders::Receipt", "Surgeries::Receipt"].include?(f.object.class.name)
	%li.nav-item
		= button_tag "#{icon('fas', 'comment')} Observación".html_safe, type: :button, aria: {selected: false, controls: 'observation'}, data: {toggle: 'tab', target: '#observation'}, class: 'nav-link bg-white collapsed'
- if f.object.disabled? && !f.object.canceled? && !["Surgeries::Consumption", "Sales::Bill", "Purchases::Bill", "Surgeries::Bill", "Surgeries::ClientBill", "Surgeries::SupplierBill", "Tenders::Bill", "Purchases::PaymentOrder", "ExpedientReceipt", "Sales::Shipments", "Surgeries::Shipments"].include?(f.object.class.name)
	%li.nav-item
		= link_to "#{icon('fas', 'backspace')} Solicitar reapertura".html_safe, [:open, f.object], class: 'nav-link bg-white collapsed btn-outline-danger text-danger', data: {"skip-pjax" => true}
- if f.object.disabled? && !f.object.canceled? && f.object.class.name == "Surgeries::Consumption" && (current_user.admin? || current_user.company_owner? || current_user.roles.where(id: 21).any?)
	%li.nav-item
		= link_to "#{icon('fas', 'backspace')} Solicitar reapertura".html_safe, [:open, f.object], class: 'nav-link bg-white collapsed btn-outline-danger text-danger', data: {"skip-pjax" => true}
- if f.object.has_pdf?
	%li.nav-item
		= pdf_button(f.object)
- if f.object.file.try(:surgery_request)
	%li.nav-item
		= button_tag "#{icon('fas', 'list')} Solicitud".html_safe, type: :button, aria: {selected: true, controls: 'surgery_request'}, data: {toggle: 'tab', target: '#surgery_request', target: '#surgery_request'}, class: 'nav-link bg-white'

app/views/sales/_shared_nav.html.haml
= link_to icon('fas', 'chevron-left'), :back, class: 'btn btn-sm text-dark'
- if document.persisted?
	%ul.nav.nav-tabs.mx-4.border-bottom-0.justify-content-center
		%li.title.nav-item.border-right
			= link_to  "#{icon('fas', 'list')} Ventas".html_safe, sales_files_path(), class: 'btn btn-light float-left'
		%li.nav-item
			= link_to "Expediente", sales_file_path(document.file_id), class: 'nav-link'
		- unless document.file.is_counter_sale?
			%li.nav-item.dropdown
				= link_to "Solicitudes", "#", data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: true, expanded: false}, class: "nav-link dropdown-toggle #{'active' if document.class.name == 'Sales::SaleRequest'}"
				.dropdown-menu
					- document.file.sale_requests.each do |request|
						= link_to "Nº #{request.number}", edit_sales_sale_request_path(request.id), class: 'dropdown-item'
					- unless document.file.disabled?
						= link_to "#{icon('fas', 'plus')} Generar solicitud".html_safe, new_sales_sale_request_path(file_id: document.file_id), class: 'dropdown-item'
			%li.nav-item.dropdown
				= link_to "Presupuestos", "#", data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: true, expanded: false}, class: "nav-link dropdown-toggle #{'active' if document.class.name == 'Sales::Budget'}"
				.dropdown-menu
					- document.file.budgets.each do |budget|
						= link_to "Nº #{budget.number}", edit_sales_budget_path(budget.id), class: 'dropdown-item'
					- unless document.file.disabled?
						= link_to "#{icon('fas', 'plus')} Generar presupuesto".html_safe, new_sales_budget_path(file_id: document.file_id), class: 'dropdown-item'
			%li.nav-item.dropdown
				= link_to "Ordenes", "#", data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: true, expanded: false}, class: "nav-link dropdown-toggle #{'active' if document.class.name == 'Sales::Order'}"
				.dropdown-menu
					- document.file.orders.each do |order|
						= link_to "Nº #{order.number}", edit_sales_order_path(order.id), class: 'dropdown-item'
					- unless document.file.disabled?
						= link_to "#{icon('fas', 'plus')} Generar orden".html_safe, new_sales_order_path(file_id: document.file_id), class: 'dropdown-item'
			%li.nav-item.dropdown
				= link_to "Compras", "#", data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: true, expanded: false}, class: "nav-link dropdown-toggle"
				.dropdown-menu
					- document.file.purchase_requests.each do |purchase|
						= link_to "Nº #{purchase.number}", edit_purchases_purchase_request_path(purchase.id), class: 'dropdown-item'
		%li.nav-item.dropdown
			= link_to "Facturación", "#", data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: true, expanded: false}, class: "nav-link dropdown-toggle #{'active' if document.class.name == 'Sales::Bill'}"
			.dropdown-menu
				- document.file.bills.each do |bill|
					= link_to bill.name(:short), edit_sales_bill_path(bill.id), class: 'dropdown-item'
				- unless document.file.disabled?
					= link_to "#{icon('fas', 'plus')} Registrar comprobante".html_safe, new_sales_bill_path(file_id: document.file_id), class: 'dropdown-item'
		%li.nav-item.dropdown
			= link_to "Remitos", "#", data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: true, expanded: false}, class: "nav-link dropdown-toggle #{'active' if document.class.name == 'Sales::Shipment'}"
			.dropdown-menu
				- document.file.shipments.each do |shipment|
					= link_to "Nº #{shipment.number}", edit_sales_shipment_path(shipment.id), class: 'dropdown-item'
				- unless document.file.disabled?
					= link_to "#{icon('fas', 'plus')} Registrar remito".html_safe, new_sales_shipment_path(file_id: document.file_id), class: 'dropdown-item'

app/views/sales/shared_sender.text.haml
Se adjunta comprobante